### PR TITLE
New Socket.io

### PR DESCRIPTION
**Pull request by salishdev**
EasyWebsocket hasn't been working in Chrome since version 14 went stable (with the hybi10 specification).  I decided to upgrade socket.io to the newest.  Everything seems to work well.  I thought I would share.

### CODE REVIEW

**Comment by jeromeetienne** [comment]
nice one :) no porting trouble ?

**Comment by jeromeetienne** [comment]
it seems good. i will merge it this weekend. meanwhile can you reenable the default address ?

**Comment by salishdev** [comment]
Sure.

**Comment by jeromeetienne** [comment]
Merged. thanks the contribution :)

**Pull request merged**
